source 'https://github.com/CocoaPods/Specs.git'
source 'https://bitbucket.org/DVALibs/dvapods.git'

#use_frameworks!

target 'DVAManagers_Example', :exclusive => true do
  pod "DVAManagers", :path => "../"
end

target 'DVAManagers_Tests', :exclusive => true do
  pod "DVAManagers", :path => "../"
  pod "DVANetworkTestStubs" , '~> 1.0.0'
end


